name: teamcoronel
region: nyc

static_sites:
- name: web
  source_dir: teamcoronel
  index_document: index.html
  routes:
  - path: /

functions:
- name: coach
  source_dir: teamcoronel/packages/coach
  routes:
  - path: /api/coach

- name: sheets
  source_dir: teamcoronel/packages/sheets
  routes:
  - path: /api/sheets
