packages:
  - name: api
    actions:
      - name: coach
        binary: false
        main: ''
        runtime: 'nodejs:default'
        web: true
        environment:
          ANTHROPIC_API_KEY: '${ANTHROPIC_API_KEY}'
        limits:
          timeout: 120000
          memory: 1024
